NVCC = nvcc
CC = mpiCC

NVCC_FLAGS = -Xcompiler -march=native -arch=sm_35 -O3 -lmpi
# Next line fixes a clash with nvcc parser and boost
NVCC_FLAGS +=-DBOOST_NOINLINE='__attribute__ ((noinline))'
CCFLAGS = -O3 -std=c++11
CUDAFLAGS=-I${CUDA_PATH}/include -L$(CUDA_PATH)/lib64 -lcuda -lcudart

# Libraries
LIBRARY_PREFIX = $(USERAPPL)/openmpi/libraries
MPI_HOME = /appl/opt/openmpi/1.8-cuda/gcc/4.8.2/

INC_BOOST = -I$(LIBRARY_PREFIX)/boost/include
LIB_BOOST = -L$(LIBRARY_PREFIX)/boost/lib -lboost_program_options

LIB_PROFILE = -L$(LIBRARY_PREFIX)/phiprof/lib -lphiprof
INC_PROFILE = -I$(LIBRARY_PREFIX)/phiprof/include

INC_MPI =-I${MPI_HOME}/include
